[phases.setup]
nixPkgs = ['nodejs_18', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    # Skip cache commands during build - they'll run at startup
]