[phases.setup]
nixPkgs = ['nodejs_18', 'php82', 'php82Packages.composer']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader',
    'npm ci',
    'npm run build'
]

[phases.build]
cmds = [
    # Skip cache commands during build - they'll run at startup
]

[start]
cmd = 'php artisan config:clear && php artisan cache:clear && php artisan config:cache && php artisan route:cache && php artisan view:cache && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT'